rozgrywki/rozgrywki/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin

from rozgrywki.core.filters import UserFilter, TeamFilter, EventFilter
from django_filters.views import FilterView
from rozgrywki.core import views as core_views
from rozgrywki.games import views as games_views
from rozgrywki.core.views import search
from rozgrywki.games.views import BracketViewSet, CreateEventViewSet, EventViewSet, TeamDetailsView, AddPlayer, RemovePlayer, AddTeam, RemoveTeam, RemoveEvent, AddGoal, AddShot, AddYellowCard, AddRedCard, MatchResume, MatchEnd

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^$', games_views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'home'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^events/$', EventViewSet.as_view(), name='events'),
    url(r'^create_event/$', CreateEventViewSet.as_view(), name='create_event'),
    url(r'^remove_event/$', RemoveEvent, name='remove-event'),
    url(r'^add_goal/(?P<pk>[0-9]+)/$', AddGoal, name='add-goal'),
    url(r'^add_shot/(?P<pk>[0-9]+)/$', AddShot, name='add-shot'),
    url(r'^add_yellowcard/(?P<pk>[0-9]+)/$', AddYellowCard, name='add-yellowcard'),
    url(r'^add_redcard/(?P<pk>[0-9]+)/$', AddRedCard, name='add-redcard'),
    url(r'^bracket/(?P<pk>[0-9]+)/$', BracketViewSet.as_view(), name='bracket'),
    url(r'^bracket/(?P<pk>[0-9]+)/edit$', games_views.EditBracket, name='bracket-edit'),
    url(r'^match/(?P<pk>[0-9]+)/$', games_views.ShowMatch, name='match-details'),
    url(r'^match/(?P<pk>[0-9]+)/edit$', games_views.EditMatch, name='match-edit'),
    url(r'^match/(?P<pk>[0-9]+)/end$', MatchEnd, name='match-end'),
    url(r'^match/(?P<pk>[0-9]+)/resume$', MatchResume, name='match-resume'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    url(r'^games/', games_views.home, name = 'games'),
    url(r'^teams/(?P<pk>\d+)$', TeamDetailsView.as_view(), name='team-details'),
    url(r'^teams/(?P<pk>\d+)/footballers/add/$', AddPlayer, name='add-player'),
    url(r'^teams/(?P<pk>\d+)/footballers/remove/$', RemovePlayer, name='remove-player'),
    url(r'^teams/add/$', AddTeam, name='add-team'),
    url(r'^teams/remove/$', RemoveTeam, name='remove-team'),
    url(r'^teams/(?P<pkTeam>\d+)/(?P<pkPlayer>\d+)$', games_views.player_detail, name='player-details'),
    url(r'^teams/$', games_views.team_view, name='team-list'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^search/', search, name = 'search'),
    url(r'^team_search/$', FilterView.as_view(filterset_class=TeamFilter,
        template_name='team_list.html'), name='team_search'),
    url(r'^user_search/$', FilterView.as_view(filterset_class=UserFilter,
        template_name='user_list.html'), name='user_search'),
    url(r'^event_search/$', FilterView.as_view(filterset_class=EventFilter,
        template_name='event_list.html'), name='event_search'),

]

rozgrywki/rozgrywki/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

rozgrywki/rozgrywki/games/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

import datetime

from django.forms import ModelForm


class Team(models.Model):
    team_name = models.CharField(max_length=20)
    short_name = models.CharField(max_length=5)
    team_owner = models.ForeignKey('auth.User',on_delete=models.CASCADE)

    def __str__(self, **kwargs):
        return self.team_name


class Player(models.Model):
    player_name = models.CharField(max_length=20)
    player_surname = models.CharField(max_length=30)
    team_name = models.ForeignKey(Team,on_delete=models.CASCADE)

    def __str__(self, **kwargs):
        return "{Name} {Surname}".format(Name=self.player_name, Surname=self.player_surname)


class TeamScore(models.Model):
    team = models.ForeignKey(Team,on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    promote = models.BooleanField(default=False)

    def __str__(self):
        return self.team.team_name


class Event(models.Model):
    name = models.CharField(max_length=50)
    teams = models.ManyToManyField(Team, related_name='event_team')
    create_user = models.ForeignKey('auth.User', blank=True, null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class TeamEvent(models.Model):
    event = models.ForeignKey(Event,on_delete=models.CASCADE)
    team_one = models.ForeignKey(TeamScore, related_name='team_one',on_delete=models.CASCADE)
    team_two = models.ForeignKey(TeamScore, related_name='team_two',on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)

    def __str__(self):
        return ' '.join([self.event.name, self.team_one.team.team_name, self.team_two.team.team_name])


class Match(models.Model):
    Date = models.DateField("Date", default=datetime.datetime.today)
    Host = models.ForeignKey(Team, related_name="A",on_delete=models.CASCADE)
    Guest = models.ForeignKey(Team, related_name="B",on_delete=models.CASCADE)
    Round = models.DecimalField(max_digits=2, decimal_places=0)

    def __str__(self):
        return "{Host} vs {Guest}".format(Host=self.Host.Name, Guest=self.Guest.Name)


class GlobalStat(models.Model):
    Match = models.ForeignKey(Match,on_delete=models.CASCADE)
    HostScore = models.DecimalField(max_digits=2, decimal_places=0)
    GuestScore = models.DecimalField(max_digits=2, decimal_places=0)
    HostPoints = models.DecimalField(max_digits=2, decimal_places=0)
    GuestPoints = models.DecimalField(max_digits=2, decimal_places=0)

    def __str__(self):
        return "{Host} vs {Guest}".format(Host=self.Match.Host.Name, Guest=self.Match.Guest.Name)

class Goal(models.Model):
    match = models.ForeignKey(TeamEvent,on_delete=models.CASCADE)
    player = models.ForeignKey(Player,on_delete=models.CASCADE)
    time = models.IntegerField(default=0)

    def __str__(self):
        return "{Match} {Player} {Time} {Team}".format(Match=self.match, Player=self.player, Time=self.time)


class Shot(models.Model):
    match = models.ForeignKey(TeamEvent,on_delete=models.CASCADE)
    player = models.ForeignKey(Player,on_delete=models.CASCADE)
    time = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class YellowCard(models.Model):
    match = models.ForeignKey(TeamEvent,on_delete=models.CASCADE)
    player = models.ForeignKey(Player,on_delete=models.CASCADE)
    time = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class RedCard(models.Model):
    match = models.ForeignKey(TeamEvent,on_delete=models.CASCADE)
    player = models.ForeignKey(Player,on_delete=models.CASCADE)
    time = models.IntegerField(default=0)

    def __str__(self):
        return self.name

rozgrywki/rozgrywki/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exists():
            raise forms.ValidationError(u'Podany adres email juz istnieje.')
        return email

rozgrywki/rozgrywki/games/forms.py
from django import forms

from rozgrywki.games.models import Event, Team


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('team_name',)


class EventForm(forms.ModelForm):
    name = forms.CharField(max_length=50)
    teams = forms.ModelMultipleChoiceField(queryset=Team.objects.all())

    class Meta:
        model = Event
        fields = ('name', 'teams')



    def __init__(self, *args, **kwargs):
        self.request = None
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(EventForm, self).__init__(*args, **kwargs)
        if self.request:
            self.fields['teams'].queryset = Team.objects.filter(team_owner=self.request.user)

rozgrywki/rozgrywki/core/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string

from rozgrywki.core.forms import SignUpForm
from rozgrywki.core.tokens import account_activation_token
from django.core.mail import send_mail
from .filters import UserFilter


def home(request):
    return render(request, 'home.html')


def search(request):
    return render(request, 'search.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            send_mail('Rozgrywki rejestracja', message, 'projekt_rozgrywki@o2.pl', [user.email])

            return redirect('account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('home')
    else:
        return render(request, 'account_activation_invalid.html')


def user_search(request):
    user_list = User.objects.all()
    user_filter = UserFilter(request.GET, queryset=user_list)
    return render(request, 'user_list.html', {'filter': user_filter})


def team_search(request):
    team_list = Team.objects.all()
    team_filter = TeamFilter(request.GET, queryset=team_list)
    return render(request, 'team_list.html', {'filter': team_filter})


def event_search(request):
    event_list = Event.objects.prefetch_related("user_set")
    event_filter = EventFilter(request.GET, queryset=event_list)
    return render(request, 'team_list.html', {'filter': event_filter})

rozgrywki/rozgrywki/templates/games/player_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
     <div class="view-list">
         {% for player in players %}
         <h1>{{ player.player_name }} {{ player.player_surname }}</h1>
         <h3>Drużyna: {{ team.team_name }} </h3>
             {% for gol in gole %}
                 {% if gol.id == player.id %}
         <h3>Bramki: {{ gol.goals }} </h3>
                 {% endif %}
             {%  endfor %}
             {% for strzal in strzaly %}
                 {% if strzal.id == player.id %}
                    <h3>Strzały: {{ strzal.shots }} </h3>
                 {% endif %}
             {%  endfor %}
             {% for zoltakartka in zoltekartki %}
                 {% if zoltakartka.id == player.id %}
                     <h3>Żółte Kartki: {{ zoltakartka.yellowcards }} </h3>
                 {% endif %}
             {%  endfor %}
             {% for czerwonakartka in czerwonekartki %}
                 {% if czerwonakartka.id == player.id %}
                     <h3>Czerwone Kartki: {{ czerwonakartka.redcards }} </h3>
                 {% endif %}
             {%  endfor %}
         {% endfor %}
     </div>
</div>
{% endblock %}

rozgrywki/rozgrywki/templates/games/team_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1 align="center">{{ team.team_name }}</h1>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Nr</th>
                        <th>Imie</th>
                        <th>Nazwisko</th>
                        <th>Akcje</th>
                    </tr>
                    </thead>
                    {% for player in team.player_set.all %}
                        <tbody>
                        <tr>
                            <td class="col-md-1">{{ forloop.counter }}</td>
                            <td class="col-md-5">{{ player.player_name }}</td>
                            <td class="col-md-3">{{ player.player_surname }}</td>
                            <td class="col-md-5">
                                <a href="{% url 'player-details' team.id player.id %}" class="btn btn-info"
                                   role="button" style="float: left; margin-right: 4px">Informacje</a>
                                {% if user.is_authenticated %}
                                <form id="{{ player.id }}" method="post" style="float: left">{% csrf_token %}
                                    {% csrf_token %}
                                    <input type="hidden" name="player_name" value="{{ player.player_name }}">
                                    <input type="hidden" name="player_surname" value="{{ player.player_surname }}">
                                    <input type="submit" class=" btn btn-danger"
                                           onclick="document.getElementById('{{ player.id }}').action='{% url 'remove-player' object.id %}'"
                                           value="Usuń"/>
                                </form>
                                {% endif %}
                            </td>
                        </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
            {% if user.is_authenticated %}
            <br><h3>Dodaj zawodnika</h3>
            <form id="form" method="post">{% csrf_token %}
                <label>Name</label>
                <input type="text" name="player_name">

                <label>Surname</label>
                <input type="text" name="player_surname">

                <input type="submit" class="btn btn-success" onclick="document.getElementById('form').action='{% url 'add-player' object.id %}'"
                       value="Dodaj"/>
            </form>
            {% endif %}
    </div>
{% endblock %}

rozgrywki/rozgrywki/templates/games/team_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        {% if user.is_authenticated %}
            <h3>Lista drużyn użytkownika {{ user.username }}</h3>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Nr</th>
                        <th>Drużyna</th>
                        <th>Skrót</th>
                        <th>Akcje</th>
                    </tr>
                    </thead>
                    {% for team in teams %}
                        <tbody>
                        <tr>
                            <td class="col-md-1">{{ forloop.counter }}</td>
                            <td class="col-md-5">{{ team.team_name }}</td>
                            <td class="col-md-3">{{ team.short_name }}</td>
                            <td class="col-md-5">
                                <a href="{% url 'team-details' team.id %}" class="btn btn-warning"
                                   role="button" style="float: left; margin-right: 4px">Edytuj</a>
                                <form id="{{ team.team_name }}" method="post" style="float: left">{% csrf_token %}
                                  {% csrf_token %}
                                  <input type="hidden" name="team_name" value="{{ team.team_name }}">
                                    <input type="submit" class=" btn btn-danger" onclick="document.getElementById('{{ team.team_name }}').action='{% url 'remove-team' %}'"
                                           value="Usuń"/>
                                </form>
                            </td>
                        </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
            <br><h3>Dodaj drużynę</h3>
            <form id="form" method="POST" name="add-team">{% csrf_token %}
                <label>Nazwa drużyny: </label>
                <input type="text" name="team_name">

                <label>Skrót: </label>
                <input type="text" name="short_name">

                <input type="submit" class="btn btn-success" onclick="document.getElementById('form').action='{% url 'add-team' %}'"
                       value="Dodaj"/>
            </form>
        {% endif %}
    </div>
{% endblock %}